# Generated by Django 2.2.19 on 2022-03-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0003_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='requested_amount',
        ),
    ]
