# Generated by Django 2.2.19 on 2022-03-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0004_remove_reply_requested_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='updated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated_dt',
        ),
    ]
